### ISSUE TITLE
Can't install the add-on on Blender 4.0.2

### ISSUE THREAD

**Issue by xan2622** [MarshmallowCirno/RadialDuplicator#1]
Hi. 

After downloading the add-on from this Github repository (with the green CODE button > Download ZIP).
... Installing the `RadialDuplicator-main.zip` file in Blender 4.0.2 works **but activating it does not**.

![screenshot](https://github.com/MarshmallowCirno/RadialDuplicator/assets/1732773/aeffb193-608b-44e4-a9e4-5ed1ec2aa38f)

**Comment by MarshmallowCirno** [comment]
Hi. That button will download repository. Add-on is inside the directory `object_radial_duplicator` of the repository. Only that folder should be unpacked. I added zip with the add-on only to [releases](https://github.com/MarshmallowCirno/RadialDuplicator/releases) try it instead.

**Comment by xan2622** [comment]
Yeah, I also found that it was because of the directory tree (inside the ZIP file).
Thank you for providing an easy installable add-on on the Releases page.
